[package]
name = "mild-style"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grass = "0.11.2"
css-minify = "0.2.2"