[package]
name = "mild-docs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mild-core = {path = "../core"}
yew = "0.19.3"
yew-router = "0.16.0"