pub mod merge_two_lists;
pub mod print_common_part;
pub mod remove_double_last_kth_node;
mod remove_elements;
pub mod remove_single_last_kth_node;
pub mod reverse_list;
mod reverse_list2;
mod is_palindrome;
mod reverse_print;
mod single_link;