[package]
name = "mild-docs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mild-core = {path = "../mild-core"}
yew = {version = "0.20.0",  features = ["csr"]}
yew-router = "0.17.0"
