[package]
name = "mild-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-timers = "^0.2.4"
web-sys = "^0.3.60"
yew = "^0.20.0"
